import { type NextPage } from "next";
import Head from "next/head";
import styles from "./index.module.css";
import { Container, Grid } from "@mui/material";
import Header from '../components/Header/Header';
import { useEffect, useState } from "react";
import Favorites from "../components/Favorites/Favorites";
import Gif from "../components/Gifs/Gifs";


const API_KEY = "TxOoZ8YwdSgHxMJ21kI2eboPeBYdUrmo";
interface Gif {
  id: string;
  url: string;
  title: string;
}

const Home: NextPage = () => {
  const [gifs, setGifs] = useState<Gif[]>([]);
  const [favorites, setFavorites] = useState<Gif[]>([]);


  const handleAddToFavorites = (gif: Gif) => {
    const isAlreadyInFavorites = favorites.some(
      (favorite) => favorite.id === gif.id
    );
    if (!isAlreadyInFavorites) {
      setFavorites([gif]);
    }
  };

  useEffect(() => {
    const savedFavorites = localStorage.getItem("favorites");
    const initialFavorites: Gif[] = savedFavorites
      ? JSON.parse(savedFavorites)
      : [];
    setFavorites(initialFavorites);
  }, []);

    useEffect(() => {
    localStorage.setItem("favorites", JSON.stringify(favorites));
  }, [favorites]);

  return (
    <>
      <Head>
        <title>It's your Gif?</title>
        <meta name="cool website by Xander Rybalov" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="md">
        <Header
            apiKey={API_KEY}
            onSearch={(newGifs: Gif[]) => {
              setGifs(newGifs);
            }}
        />
      <Favorites favorites={favorites} />
      </Container>
      <Container maxWidth="md">
				<Grid container spacing={2}>
        {gifs.map((gif) => (
        <Gif key={gif.id} gif={gif} onAddToFavorites={handleAddToFavorites} />
      ))}
				</ Grid>
			</Container>
    </>
  );
};

export default Home;


{/*<div className={styles.profile}>
<div className={styles.profileImage}>
  <img src="https://images.unsplash.com/photo-1513721032312-6a18a42c8763?w=152&h=152&fit=crop&crop=faces" alt=""/>
</div>
<div className={styles.profileUserSettings}>
  <h1 className={styles.profileUserName}>Xander Rybalov</h1>
  <button className={styles.profileEditBtn}>Edit Profile</button>
</div>
</div>*/}